# Generated by Django 6.0 on 2025-12-09 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('selectivity', models.CharField(choices=[('high', 'Высокая селективность'), ('medium', 'Средняя селективность'), ('low', 'Низкая селективность')], default='medium', max_length=10)),
                ('website_url', models.URLField(blank=True)),
                ('main_deadline', models.DateField(blank=True, null=True)),
                ('min_profile_score', models.PositiveIntegerField(blank=True, help_text='Условный минимальный скор профиля от 0 до 100', null=True)),
                ('avg_profile_score', models.PositiveIntegerField(blank=True, help_text='Условный средний скор профиля от 0 до 100', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('reach', 'Reach'), ('target', 'Target'), ('safety', 'Safety')], default='target', max_length=10)),
                ('status', models.CharField(choices=[('planning', 'Планирую'), ('preparing', 'Готовлюсь'), ('applying', 'Подаюсь'), ('submitted', 'Отправлено'), ('admitted', 'Принят'), ('rejected', 'Отказ')], default='planning', max_length=15)),
                ('tests_done', models.BooleanField(default=False)),
                ('essays_done', models.BooleanField(default=False)),
                ('recommendations_done', models.BooleanField(default=False)),
                ('application_form_done', models.BooleanField(default=False)),
                ('application_fee_paid', models.BooleanField(default=False)),
                ('deadline_override', models.DateField(blank=True, help_text='Если личный дедлайн отличается от основного', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_universities', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_universities', to='universities.university')),
            ],
            options={
                'unique_together': {('student', 'university')},
            },
        ),
    ]
