# Generated by Django 6.0 on 2025-12-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="activities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="budget_range",
            field=models.CharField(
                blank=True,
                choices=[("low", "Низкий"), ("medium", "Средний"), ("high", "Высокий")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="det_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="det_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="grades_summary",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="graduation_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="honors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="ielts_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="intended_major",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sat_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="toefl_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
